remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: tomjoht/documentation-theme-jekyll

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Delphix Workshop Guides
logo: /assets/logo.svg